### ISSUE TITLE
Standalone Mode

### ISSUE THREAD

**Issue by mvahowe** [Proskomma/epitelete#27]
The idea is to be able to load a PERF document as JSON, potentially received via HTTP or from the FS. This removes the need to use Proskomma, and offers the potential to load, edit, save and reload data, like a real editor!

The signature of the loading function is `sideloadPerf(bookCode, PerfJSON)`

We'd also need to change some of the other behaviour since, eg
- `fetchPerf` makes no sense without Proskomma
- `readPerf` can't therefore call `fetchPerf`
- `bookHeaders` cannot look up anything in Proskomma, but could return the headers for the loaded documents

I suggest
- adding a key called `backend` which is set to either `proskomma` or `standalone`
- setting that key to `proskomma` in the existing constructor
- adding a new constructor `new Epitelete(docSetId)` which sets backend to `standalone` and the proskomma key to null (we could also consider one constructor that takes a single object with named keys, which might be more transparent)
- implementing `sideloadPerf`and include a guard to throw an error if called in `proskomma` mode
- adding a guard to `fetchPerf` to throw an error if called in `standalone` mode
- adding an alternative implementation of `bookHeaders` that returns the local document headers in `standalone` mode

and then there are a few things to test...

**Comment by mandolyte** [comment]
Why not just add PK as an argument to readPerf() and eliminate the fetchPerf?

No standalone mode needed.
@mvahowe

**Comment by mandolyte** [comment]
@mvahowe I spent some thinking about how standalone mode could be used to resume a prior editing session. Thus not really "standalone" but a lot of overlap in what's needed. I revised my "big picture" post to include this as well as some detail on using Epitelete from a script which might *really* be standalone. Here is the expansion:

# Big Picture

- A set of documents is imported into Proskomma (PK) by the application.
	- The application owns the Proskomma instance
	- This will be one or more books of the Bible in USFM format.
	- The instance will be passed to Epitelete 
- The editor will request a book, which will be returned in PERF JSON format to the editor.
	- The requesting method is `Epitelete.readPerf` with bookCode as the sole argument
	- *Alternatively,* the editor may have stored the PERF JSON and may wish to resume editing. Then the method to use is: `Epitelete.loadPerf`. The argument is the PERF JSON that the app had saved in the prior editing session.
- The editor will convert the PERF into HTML which then may be rendered for the user to view or make changes. 
	- The method to do this is: `readHtml` . This method is not in Epitelete itself, but on a subclass of Epitelete that adds this method.
- When there is a change at the PERF Sequence level, then the editor will call the `writeHtml()` method of the Epitelete subclass.
- The editor will call this function with three arguments:
	- the document book code
	- the sequence id
	- the HTML content
- This function will extract the sequence from the HTML and will run the super class method "writePerf()"
- This function actually updates the original PERF JSON with the changed content. It does not "write" it anywhere. It will do the following steps:
	- Validate the sequence 
	- If valid, then the sequence will be merged into the document.
	- The document as a whole will be validated and, if valid, returned to the editor
	- If not valid, then an exception will be thrown
- At the end of the editing, a new method (not yet defined) will be used to supply the PERF to the PK instance to update the document in PK. For example, it might be named "savePerf".

## Standalone Mode
We will need to use Epitelete in standalone mode. Standalone mode means to use it without reference to a PK instance.

In this usage, use the `loadPerf` method instead of `readPerf`. From that point forward, usage is the same as above since `writePerf` does not reference the PK instance.

Of course, the app can do both:
- It will use `readPerf` when it needs a different book.
- It will use `loadPerf` when it needs to resume a prior editing session.

Another use of standalone mode is in a script. Here only `loadPerf` and `writePerf` are needed. If no PK instance is provided, the constructor will need to handle *null* for the PK instance. And if `readPerf` is used by mistake, an exception will be thrown.
